language: ruby
rvm:
 - 2.5.1
cache:
  bundler: true
  directories:
    - node_modules
    - /home/travis/.rvm/
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install --deployment
  - yarn install